DATASETS:
  MODALITY: 'RGBDiff'
  NUM_SEGS: 3
  TRAIN:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
  TEST:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
TRANSFORM:
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  JITTER_SCALES: (256, 320)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
DATALOADER:
  TRAIN_BATCH_SIZE: 6
  TEST_BATCH_SIZE: 6
  NUM_WORKERS: 8
MODEL:
  NAME: 'TSN'
  PRETRAINED: ""
  SYNC_BN: True
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'resnet50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
  HEAD:
    NAME: 'TSNHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.0
    NUM_CLASSES: 101
  RECOGNIZER:
    NAME: 'TSNRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'sgd'
  LR: 2e-3
  WEIGHT_DECAY: 3e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 3e-4
  WARMUP:
    ITERATION: 1000
    MULTIPLIER: 1.0
TRAIN:
  MAX_ITER: 20000
OUTPUT:
  DIR: 'outputs/tsn_r50_ucf101_rgbdiff_224x224x3'